### ISSUE TITLE
Feature Request: Generate class directly from Explorer Panel

### ISSUE THREAD

**Issue by still-dreaming-1** [damian-bal/php-class-generator#2]
I don't know if this is possible or not, but it would be awesome if we could just right click the folder from the VS Code solution panel, and have a "new class" option, or something like that.

**Comment by damian-bal** [comment]
Thanks for the idea, I will look if that's possible if it is then I will try to find the time to implement it.

**Comment by still-dreaming-1** [comment]
Why was this marked as complete? I think most users are looking through the Explorer when deciding where to create a new class. It helps to be able to see the other files and folders there. This also helps when deciding what name to give your class or whatever you are creating.
