### ISSUE TITLE
Donate Option

### ISSUE THREAD

**Issue by still-dreaming-1** [damian-bal/php-class-generator#4]
I realize I opened many issues at once, and there seems to be nothing else out there like this, so I was wondering if I could donate some money to this project. If you setup a donate option on Github, I will try to donate something.

**Comment by damian-bal** [comment]
Thanks, it's nice of you, I will look into setting that up when I have a moment, but really is not important at all at this time as this project doesn't take me that so much of my time, but thanks 👍
