### ISSUE TITLE
Cannot install in vscode v.1.36

### ISSUE THREAD

**Issue by mc316** [damian-bal/php-class-generator#5]
This is the message I get when I try to install the extension:

`Unable to install 'damianbal.php-class-generator-composer-psr-4' extension because it is not compatible with the current version of VS Code (version 1.36.1).`

P.S. I also tried this with the latest version of vscode 1.45

**Comment by damian-bal** [comment]
The latest vscode version is  ' 1.45.1', and that extension supports only that version as minimum.
